# Generated by Django 3.1.1 on 2020-09-30 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebank', '0002_auto_20200928_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(help_text='User depositing', max_length=100)),
                ('account', models.IntegerField(help_text='Into which account?')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to deposit', max_digits=9)),
                ('note', models.CharField(blank=True, default='Deposit', help_text='Provide optional note/description', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Transaction date and time')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, default=2340123456789, help_text='Mobile number'),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(help_text='From which account?')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to withdraw', max_digits=9)),
                ('note', models.CharField(blank=True, default='Withdrawal', help_text='Provide optional note/description', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Transaction date and time')),
                ('user', models.ForeignKey(help_text='User withdrawing', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(help_text='Account number to be tranfer to')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to transfer', max_digits=9)),
                ('note', models.CharField(blank=True, default='Transfer', help_text='Provide optional note/description', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Transaction date and time')),
                ('user', models.ForeignKey(help_text='User transferring', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(help_text='Account number to be tranfer to')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to transfer', max_digits=9)),
                ('token', models.IntegerField(help_text='Six digit Bank Token', unique=True)),
                ('note', models.CharField(blank=True, default='Transfer', help_text='Provide optional note/description', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Transaction date and time')),
                ('user', models.ForeignKey(help_text='User transferring', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
